name: Deploy Dist
on : [push , workflow_dispatch]
jobs:
    deploy-test:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to test environment
              run: |
                echo "repo cloning"
                echo "${{toJson(github)}}"
                echo git clone https://github.com/${{github.repository}}.git
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: print node version
              run: node -v
            - name: install npm dependencies
              run : npm install
            - name: Run tests
              run : npm run test